### ISSUE TITLE
BETA: Change About-Button links to internal Popups

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#174]
In anticipation and preparation for the *Beta* stage of our application, we need to convert the help and information related links on the "About" page, from external web site (GitHub) links, to internal on-device (or in code) text files. 

**Q**: Why is this an issue?

**A**: (1) It can be annoying to the user, that each button require you to start a web browser to be able to see the relevant information. (2) It may not be secure (or even possible), to browse the web at the time this information is needed. 

**Plan**: Try to make our app as silent as possible without any external IP connections, apart from download OCID (and similar) data. But that is a location dependent and once in while operation.

**Comment by E3V3A** [comment]
What code is needed to get this working? If someone can code the pop-up for one button, I can do the others.

**Comment by SecUpwN** [comment]
![Dialogs](https://developer.android.com/images/ui/dialogs.png)

We can use a  [dialogs](https://developer.android.com/guide/topics/ui/dialogs.html). Also see [this](https://developer.android.com/design/building-blocks/dialogs.html).

**Comment by E3V3A** [comment]
Ok, so what do we have to do to get this going?

**Comment by E3V3A** [comment]
@SecUpwN  or @d-mariano  I need some input here. That input should consist of a simple PoC code to make a pop-up screen like the one we already have for the "Disclaimer"...

**Comment by SecUpwN** [comment]
@banjaxbanjo, huge thanks for the first PR to fix this Issue, here is the [APK](https://buildozer.io/projects/43768/builds/14566/directdownload)! I have been testing the latest changes and would like you to have a look at a few things, hopefully not getting on your nerves with this:

1. The CreditsRoll was perfect as it was before. Have you tested if the latest change into a popup makes it easier to read on devices with smaller screens? If it doesn't, I guess we should change it back.
2. Not sure if this is an Issue with the padding, but the whole About-Page is now scrollable again. Maybe you can make the padding a little smaller so that everything fits on the site without scrolling?
3. The text `Click icons for detailed information` should be colored red or green (like in the top title).
4. The popups of the Status Icons are awesome. But when you click one of them, it would be great of the wording `DETAILED EXPLANATION` as well as the Icon and `Status xyz` could be centered. The text itself is just fine.

Please excuse my nitpickyness, I hope you'll understand that I'm a very visual person.

**Comment by banjaxbanjo** [comment]
Thanks mate,

Ive only installed on galaxy s5 and didnt have scroll isssues but will install on smaller device and try fix this scroll issue. Probably something to do with the click icons textview.

The others are a quick fix will look into them later whem at computer and fix asap with your recommendations.

I will also revert the credits to a non dialog was really a test to see what it looked like.

Cheers
Paul 

Sent from Yahoo Mail on Android

**Comment by SecUpwN** [comment]
> I will also revert the credits to a non dialog was really a test to see what it looked like.

Before you revert that one, please have a look at which one looks better on both devices. Thank you for digging into the small things I just mentioned, I guess after those this Issue should really be done.
