### ISSUE TITLE
Incorrect Silent SMS Detection: MNO dependent

### ISSUE THREAD

**Issue by MatejKovacic** [SecUpwN/Android-IMSI-Catcher-Detector#178]
Hi, I installed AIMSICD, v 0.1.24-alpha(24) to a mobile phone with Android 4.4.2.

That phone was registerd to slovenian mobile operator Si.mobil (operator's code is 29340, https://en.wikipedia.org/wiki/Si.mobil).

I send an ordinary test SMS message to that phone from Telekom Slovenije network, and it was normally received. Then I sent an ordinary test SMS message to that phone from Si.mobil network, and AIMSICD detected it as a silent SMS. That detection was not correct.

I received several reports of this incorrect detection of all SMS'es coming from Si.mobil network as silent messages from several users.

P. S. I am willing to do some additional testing if neccessary.

**Comment by E3V3A** [comment]
Any progress on this? Seem like the #252 is related.

**Comment by SecUpwN** [comment]
@MatejKovacic, would you please recompile our current code and check if this is still valid?

**Comment by E3V3A** [comment]
Silent SMS is not yet implemented. Changing the code here will not help in this case. No need to recompile if nobody made any changes.

**Comment by MatejKovacic** [comment]
Hi, are there detailed instructions how to compile the code? Unfortunately, I am not developer. However, I am a Linux user, and know some basics (how to do configure, make and make install), but I have never compiled anything for Android.

Or, if you have some nightly version...

**Comment by SecUpwN** [comment]
Hey @MatejKovacic, didn't you discover our [WIKI](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki) yet? You'll find the [detailed build instrcutions](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Building) there as well, should be straight-forward. We will be having a **fresh release** this week, we are aiming at Wednesday at the latest.

**Comment by E3V3A** [comment]
@MatejKovacic  Send me an email, and I'll send you the latest build and link to our internal testing chat room. Your testing is interesting and I'd like to see a better logcat of these events. But you'll need to provide more details about your phone model/ROM and the logcat you posted is no longer there.

**Comment by MatejKovacic** [comment]
Hi, soory for my late response... well, I installed the latest version, and there is the same error. Yes, I overlooked build instructions, I have checked them now and they seen quite straightforward.

Anyway, my e-mail is matej dot kovacic and then at and owca dot info.

**Comment by MatejKovacic** [comment]
Just a short question... who is David Santiago? Can I keep him on my block list?

**Comment by SecUpwN** [comment]
>Just a short question... who is David Santiago? Can I keep him on my block list?

You mean user "Davidmylove"? Yes, you may keep him on the block list.

**Comment by E3V3A** [comment]
It appears there is something wrong with the `MTI=0` assumption. Perhaps the line: 
```
if (pID == 0x40 || mti == 0) {
```
should be:
```
if (pID == 0x40 && mti == 0) {
```
?

Please read the 3GPP/GSM [03.40](http://en.wikipedia.org/wiki/GSM_03.40) specifications.

**Comment by banjaxbanjo** [comment]
@E3V3A hey mate, question are ye using the broadcast receiver to catch the silent sms? The receiver wont detect my silent sms sent from my app or wap push sms?

**Comment by E3V3A** [comment]
@banjaxbanjo I think so, but since I didn't develop the code for it, I'm not sure. If you can see it in logcat (as explained in issue #69), you should be able to detect it. Can you? The latest commits fixes the issue where any SMS with MTI=0 is detected as silent, which is wrong. We haven't made any release or tests with this yet...but I expect us to be able to close this when we do.

**Comment by banjaxbanjo** [comment]
@E3V3A 

Deleted and reposted commet here

The good news is it can be picked up with logcat but I dont think the broadcast receiver method will capture it since the sms is discarded before its sent to the broadcast receiver..

*** logcat data
W/GSM     (  630): MWI in DCS for Vmail. DCS = 192 Dont store = true vmail count = 0
V/GSM     (  630): SMS message body (raw): '@Z£Hì@ò@f@0¥Δø¡9'
D/SMS     (  630): New SMS Message Received
D/SMS     (  630): strDeviceStorageFull = 0
D/GSM     (  630): [GsmSMSDispatcher]isTypeZero=false
D/GSM     (  630): [GsmSMSDispatcher]isUsimDataDownload=false
D/GSM     (  630): [GsmSMSDispatcher]isMWISetMessage=false
D/GSM     (  630): [GsmSMSDispatcher]isMWIClearMessage=true
D/GSM     (  630): [GsmSMSDispatcher]updateMessageWaitingIndicator:mwi=0
D/GSM     (  630): Received voice mail indicator clear SMS shouldStore=false
D/GSM     (  630): [GsmSMSDispatcher]handled=true
D/SMS     (  630): result=1,handled=true
D/GSM     (  630): [GsmSMSDispatcher]resultToCause:rc=1
``
Not type Zero but in still technically a silent sms and can be used to track a person cell by cell.

This android inner class handles these type of sms
com.android.internal.telephony.gsm.GsmSMSDispatcher
// Special case the message waiting indicator messages
boolean handled = false;
if (sms.isMWISetMessage()) {
mPhone.setVoiceMessageWaiting(1, -1); // line 1: unknown number of msgs waiting
handled = sms.isMwiDontStore();
if (VDBG) {
Rlog.d(TAG, "Received voice mail indicator set SMS shouldStore=" + !handled);
}
} else if (sms.isMWIClearMessage()) {
mPhone.setVoiceMessageWaiting(1, 0); // line 1: no msgs waiting
handled = sms.isMwiDontStore();
if (VDBG) {
Rlog.d(TAG, "Received voice mail indicator clear SMS shouldStore=" + !handled); }
}

If the phone is rooted we could parse the data with an AsyncTask to monitoring the logcat -b radio
    try {
        Runtime r = Runtime.getRuntime();
        Process process = r.exec("su");
        dos = new DataOutputStream(process.getOutputStream());
        dos.writeBytes("logcat -b radio\n");
        dos.flush();

        dis = new DataInputStream(process.getInputStream());
    } catch (IOException e) {
        e.printStackTrace();
    }
****PARSING FUNCTION GOES HERE************
With this method every sms is catchable.

**Comment by E3V3A** [comment]
> If the phone is rooted we could parse the data with an AsyncTask to monitoring the `logcat -b radio`
That's what I want to do, and in fact started to do in Bash (mksh) script. But we need to do this in java. Also, according to @tobykurien, there seem to be some issues, when using unix pipes ("|") from SU command line within Java. This is probably also deeply related to the AT command issues #23 we're having, where we're trying to parse the output of `ls | grep ...` like constructions, while shell have to stay active. 

So, if you can write a function to report a true/false, given a list of REGEX to look for in logcat, we can probably implement it immediately. Thinking: `SmsLogcatScrape(<StringArray>)`

**Comment by banjaxbanjo** [comment]
@E3V3A what i do is spilt the incomming buffered data by a new line this leaves me with an array of Items from there I look for a string that contains unique id's like [GsmSMSDispatcher]isTypeZero=false. No grep or anything like that is needed then and is all parsed by android api.

**Comment by banjaxbanjo** [comment]
@E3V3A I will work on a class that monitors logcat to parse data and extract any useful sms data. This asynctask class can be started and stopped from the main activity or where ever. It continuously gets data from logcat -d radio if a type 0 or silent sms is detected the onprocessupdate can be called and from here you can talk to the main activity to alert user about sms.

**Comment by E3V3A** [comment]
@banjaxbanjo Your logcat is interesting because it looks different from what we have seen so far. What kind of device do you have? Give me some data so that I can fill this [Test Device](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Testing-Devices) table out. 

In my [bash attempts](https://github.com/E3V3A/CounterCat/blob/master/catch0sms.sh) to scape logcat I've been using strings like: 
```bash
# Samsung GT-I9195:JB4.2.2E:MSM8930
ZSMS1="Received short message type 0"
ZSMS2="SMS_ACKNOWLEDGE true 0"
ZSMS3="Inside qmi_client_decode_msg_async  Callback"

#-b main
# W/Gsm/SmsMessage( 1195): 1 - Unsupported SMS data coding scheme 4
# D/WAP PUSH( 1195): Rx: acacacacacacacacacacacacacacacacac
# D/SmsProvider( 1195): insert content://sms/2450 succeeded
ZSMS4="Unsupported SMS data coding scheme 4"
ZSMS5="WAP PUSH"
ZSMS6="insert content://sms/"

#-b events
#I/power_partial_wake_state(  852): [1,SMSDispatcher]
#I/power_partial_wake_state(  852): [0,SMSDispatcher]
ZSMS7="[1,SMSDispatcher]"

#-b radio
#01-16 01:00:19.017 D/RILJ    ( 1226): [23715]> SMS_ACKNOWLEDGE false 214
ZSMS7="> SMS_ACKNOWLEDGE false"
```

**Comment by banjaxbanjo** [comment]
@E3V3A can you contact on my github email mate i can send you my debug info etc..

**Comment by E3V3A** [comment]
@banjaxbanjo I've lost you email. Can you please send me a new one. Make sure your email is in the body as well, since I use a spam masked email.

**Comment by banjaxbanjo** [comment]
@E3V3A its on source of my apps on github mate. Look at the interceptor app too for low level class. I will send you video of it in action when i get your email addres.

**Comment by E3V3A** [comment]
Message sent and Awesome video!

**Comment by jamesdwilson** [comment]
I think I'm having the same bug, on Sprint. Possibly related to Google Voice integration. Happy to send logs but not post them publicly.

**Comment by SecUpwN** [comment]
@jamesdwilson, please enter the Navigation Drawer and press `Debugging` to send the logs to me.

**Comment by SecUpwN** [comment]
@jamesdwilson and @MatejKovacic, is this bug still present in the [latest release](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/releases)?

**Comment by MatejKovacic** [comment]
Hi,

just tested and bug is fixed! Thanks.

Regards,
M.
