### ISSUE TITLE
Improve Status Icon Descriptions

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#214]
Hi there, folks! This **should** be a relatively simple Issue regarding the descriptions of our [Status Icons](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Status-Icons) as suggested by @E3V3A in his https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/201#issuecomment-67246284. The `Short Explanations` and `Detailed Explanations` should be updated to reflect the current usage of oure Icons and also indicate to users how to behave without thinking too much about it. Discussion is open, let us review the current wording. Thank you!

**Comment by SecUpwN** [comment]
@E3V3A, where did you want to add the scoring table? Is it in fact the [Detection List](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/230)? Is **this** solved?

**Comment by E3V3A** [comment]
I really haven't been able to respond properly to this one, due to work load. The status icons seem fine, but they're not used in the code as I haven't  had time to finish the *detection scoring table*. But the table will appear in # 230 when done. BUT since the actual status icon descriptions are correct for now, I think we can close this, and I'll open a new issue for the implementation of these, once that score table has been clarified.
