### ISSUE TITLE
Failure to detect OpenBTS GSM station

### ISSUE THREAD

**Issue by jaredestroud** [SecUpwN/Android-IMSI-Catcher-Detector#276]
Hi,
          AIMSICD fails to detect an OpenBTS deployment as a femtocell. I am currently doing research with Ettus hardware and quick deployment GSM networks in emergency situations. I thought it would be interesting to use your app in conjunction with my research. Below, is an image of the network information along with links to the hardware/software in use (for those who are interested).

<a href="http://imgur.com/e9LbQXR"><img src="http://i.imgur.com/e9LbQXR.jpg" title="source: imgur.com" /></a>

Hardware: [B210](http://www.ettus.com/product/details/UB210-KIT)
Software [OpenBTS](http://www.ettus.com/product/details/UB210-KIT)

**Comment by SecUpwN** [comment]
Good evening and welcome to our project, @jaredestroud! Since we are currently still in [Alpha Stage](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector#alpha-stage), not all detection mechanims have been implemented. But you can help us do better! There are two Issues which should be interesting to you: #75 where we search App testers (you are perfect for this) and #6, for which detection and protection is only implemented for CDMA yet. It would be **awesome** you could help us digging deeper to solve them!

**Comment by jaredestroud** [comment]
I'll definitely look into each and see what I can do to help! 
Thanks for the quick response!

**Comment by SecUpwN** [comment]
>I'll definitely look into each and see what I can do to help!
Thanks, that would be just awesome. Happy to have you with us!

>Thanks for the quick response!

Hey, you are welcome! May I close this since you now know where we need to continue?
