### ISSUE TITLE
AIMSICD just is awesome

### ISSUE THREAD

**Issue by benutzer74** [SecUpwN/Android-IMSI-Catcher-Detector#311]
What makes AIMSICD so awesome in my mind is the fact it does not need a rooted device!
This just is great. Many people don´t want to mess with their devices and don´t want to root it.

I just went back to stock Sony ROM on my Xperia and AIMSICD works flawlessly without root :-)

But, how can it work without root? Don´t you need access to baseband logs? Snoopsnitch needs access to baseband logs and cannot work without root access due to this.

I hope you will be able to keep AIMSICD working without necessitating root access!

The question is just, will baseband makers in the future try to breach or fool such tools, I can imagine that very well!

**Comment by E3V3A** [comment]
Dear @benutzer74, 
Thanks for those great compliments and feedback. We're indeed very happy to hear that our App also works on a non-rooted device. However, as it is not meant to do this fully, due to technical restrictions, you will eventually find some limitations, regarding backup of database and accessing AT interface (not currently working anyway), and access to some system properties which improve the apps behavior to prevent false detections. 

The reason we expect to need root in the future, is that we have to read and write to the system debug and diagnostics interfaces, whose access are often crippled and/or completely undocumented. Googles general view of security by obscurity, certainly doesn't help either. Any suggestions (and we've made many) to Google on how to improve privacy and security on Android is being met with silence or at most, we'll "have a look at it", and then [0x4675636b20596f7521](http://www.rapidtables.com/convert/number/hex-to-ascii.htm) AOS/API versions later, sorry we didn't think it was important. 

I'm closing this as it's not an issue.
