### ISSUE TITLE
null deref on unrooted-device exec failure

### ISSUE THREAD

**Issue by chadmiller** [SecUpwN/Android-IMSI-Catcher-Detector#318]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.StringBuffer.toString()' on a null object reference
            at com.SecUpwN.AIMSICD.utils.ChildProcess.getResult(ChildProcess.java:166)
            at com.SecUpwN.AIMSICD.utils.CMDProcessor.runSuCommand(CMDProcessor.java:70)

**Comment by SecUpwN** [comment]
Thank you very much for your work and **WELCOME** to our project, @chadmiller! Please make sure to develop on branch `development` in the future, otherwise I will have to always sync back and forth or mess up things. Nevertheless, we very much appreciate you polishing our code - wanna give the other [Issues](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues) some pull request love, too? :smile_cat:
