### ISSUE TITLE
Kaspersky doesn't like you

### ISSUE THREAD

**Issue by snarpel** [SecUpwN/Android-IMSI-Catcher-Detector#321]
I don't know if you're aware of this, but here's what Kaspersky anti-virus says after install of 0.1.24-a-b6. 

![screenshot_2015-02-12-20-55-56](https://cloud.githubusercontent.com/assets/10982664/6176211/451579cc-b2fd-11e4-8d52-30ae1f4a3f87.png)

**Comment by E3V3A** [comment]
@snarpel  Hi and Welcome. Thank you very much for reporting this to us. 
However, my first comment is: `Ha ha ha, idiots!` 

Our second comment is that they should really tell you why they flag this app in that vague way. Is it because we have to use extensive permissions to read intercept SMS and some device properties, or because we use `su` so we can make use of rooted phones, or some other reason? It's impossible to tell. Especially since they're using heuristics. 

But if you're really concerned about malware you should probably not rely blindly on AV apps either, since the first thing a malware writer does, is testing his creations again most common AVs to try to obscure its behavior. I wonder how well it does against Fin-fisher, for example?

**Comment by SecUpwN** [comment]
@snarpel, thanks for reporting this to us. Would you please be so kind and submit to Kaspersky that our App is being detected as a false positive? Although I coonsider having an aantivitus scanner on your phone is likely to be a little overkill, I am also using one and can recommend [Avast Mobile Security](https://www.avast.com/free-mobile-security) which plays along nicely.
