### ISSUE TITLE
Neighbouring cell list not updated outside MapViewer 

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#346]
**Problem description:** 
The code in CellTracker:[updateNeighbouringCells](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/6f0287b5d603d6f088cd08deeb608c72ccc06ed0/app/src/main/java/com/SecUpwN/AIMSICD/service/CellTracker.java#L413-L547)  is only executed in MapViewer and not all the time as needed. It should be updated as soon as a new CID is connected to or every REFRESH_RATE seconds,otherwise. And obviously this should work all the time also outside of MapViewer. So to summarize, there are two problems:
 
 a) Only updated once (in MapViewer.)
 b) Never outside MapViewer.

**Solution:**
IF(*nc_list_present* AND "new CID") THEN NC list is polled.
IF(*nc_list_present*) THEN make sure NC list is polled every `REFRESH_RATE` seconds.
Where: *nc_list_present* is a global SharedPreference Boolean "variable". 

The missing NC list detection results are to be put in the `EventLog` table.

**Comment by SecUpwN** [comment]
@He3556 I am currently testing this. Would you please confirm that this is really fixed? Thanks!

**Comment by banjaxbanjo** [comment]
@He3556 This class isn't activated yet but it solves the issue of the refresh timer and automatically detects cell change rather than waiting on a timer, plus its more cpu friendly and only activates on cell change. The code the dumps the data to the database and code to send data to neighboring cells activity needs to be implimented first.

**Comment by He3556** [comment]
Hello @banjaxbanjo thank's for your support. As far as i know the code was there from the fork we are using. A few people were working on that file but nobody changed this basic polling mechanism. I read your todo list to implement your code. Right now i think we have nobody who can do it. A few things have changed since i was working on the code the last time (4 weeks ago). i need to take a look first.

**Comment by banjaxbanjo** [comment]
@He3556 ah ok so mate I will pick away it when I get a chance or maybe try impliment the listener into the cell tracker or just move related code into new class I added for easier debugging.

**Comment by He3556** [comment]
that would be brilliant mate! we planned to separate things into different classes anyway ;)
