### ISSUE TITLE
Feature Request: Audible Tone and OSM Data

### ISSUE THREAD

**Issue by swordsteel** [SecUpwN/Android-IMSI-Catcher-Detector#360]
First Request
The app has five states from green to lockdown. Would be useful for an audible tone of one repeating beep for state two (yellow), two repeating beeps for state three (orange) and so on. This is to cater to those periods when your phone is in your pocket and you don't have your eyes on the icon.

Second Request
Lobotomise gapps (google) from your app, and migrate to osm. For example Osmand can provide local maps on the device without having the device talk to the world to get map data, which in the wrong situation could be unwanted.

**Comment by SecUpwN** [comment]
Good evening @swordsteel, thank you so much for chiming in! May I ask how you found us?

About your files Issue here: As far as I know, both of these things are already been taken care of. Well, sort of. The first, the audible tone on changing threat status, is already filed in #15. Thus, this is a duplicate here. The second, migration to OSM should already be done since we're using the data provided by [OpenStreetMaps](http://www.openstreetmap.org/). If you detected any Google code, please let us know where.

**Comment by swordsteel** [comment]
Hi SecUpwN

Appreciate the feedback. I found your project while searching the net for an android app that detect cell intrusions, can't remember where exactly I found your link, xda probably.

I checked the settings and I don't find audible tone settings. Great to hear about the osm migration.

Thanks for the fine work, but I would ask is there a way to test your prog without an IMSI Catcher. Like an app that can be run from another device or a laptop with a 3d dongle?

Grats

**Comment by SecUpwN** [comment]
Good evening @swordsteel, please digg through our [open Issues](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues). You will find that most of the ideas you had (like the [Subtle alarm on IMSI-Catcher Attacks](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/15) and the [App Test Protocol](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/173)) are already added to that list, but are not coded yet. We strongly encourage you to help us by following [this simple guide](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/CONTRIBUTING.md) and submitting pull requests to add features and fix bugs. Thank you very much, please spread the word!
