### ISSUE TITLE
Repository: More Developer-Friendlyness

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#362]
This is a collection of things to solve for making our whole project much more developer friendly, easy to access and also much clearer for newcomers. I've received feedback that we've become pretty chunky and that people don't enjoy working with us due to a feeling of "being an employee working for a company". Please review **all** of our pages and let me know what and how to improve! Thank you.

- [x] Remove or reframe implications that our App doesn't work yet (e.g. in comments)
- [x] Think about using an open system like IRC instead of our current closed chat
- [x] Remove or move any overload of information from our repository (e.g. `README`)
- [x] Remove or move any unnecessary files and folders to avoid wasting bandwidth
- [x] Up-front view of detection methods on our `README` (including link to Issues)

**Comment by curtiszimmerman** [comment]
For me, contributing is just a matter of personal bandwidth. I want to contribute, but the last few months have been sketchy for me. As we move into summer, I'll have more time. But since you mention it, a dev chat on Freenode or something would be extremely nice, since I'm almost always at least idle in the dev channels of all the projects I contribute to, and it is the best way for me personally to get information I need about a project while contributing. In that regard, I've taken the opportunity to register a Freenode channel (#AIMSICD-dev). In the event you wish to migrate dev chat to Freenode, I'll transfer control of the channel to you. There is an #AIMSICD channel already on Freenode, but it is not registered and seems to have an idle operator that prevents me from registering that channel for your project as well (you must be a channel operator to register it on Freenode). I'll try to get that channel registered as well, and transfer control to you if you decide you want to use Freenode. If this is something you don't want to move forward with, I'll drop the channels.

**Comment by SecUpwN** [comment]
@curtiszimmerman thanks for chiming in! Just as a reassurance: If we have an IRC channel, will this attract more developers? As far as I know freenode prevents people from accessing it via anonymous connections like Tor, right? I'd be happy if you drop `#AIMSICD-dev` and try to get a hold of `#AIMSICD`. Once you have it, let me know and I would like to take ownership of it if possible. To transfer control, I'd have to regsiter on Freenode as well, right? I remember having registered there years ago and under another email address. Is there a way of getting back my username if password and email has been forgotten?

**Comment by curtiszimmerman** [comment]
@SecUpwN Yes, Freenode will make this project much more exposed to developers generally, I believe. Also, the thing with Freenode and Tor is ... weird. For the last couple of years or more, Tor connections were allowed, but a few weeks ago, suddenly they were not allowed (due to abuse of some kind, they say). I'm not sure what the future holds for Tor-Freenode connections, but if the past is any indication, this is a highly desirable feature for a lot of users, so it will be back. But as it stands currently, Tor connections are not allowed. You can (and most people use) a VPN to connect, or a bouncer, and also Freenode has what's called a "hostname cloak" which will prevent users from seeing your hostname/IP, but of course this is useless if you are trying to stay as anonymous as possible (when NickServ is down during some heavy DDoS, you can't auth with NickServ, and your hostname will be visible until you can authenticate with services). In order to register a channel, yes, you need an account registered with NickServ. You can retrieve your password by messaging NickServ and asking for help: `/msg NickServ help sendpass` should get you on the right track. Once you've sorted things with your account, you can `/msg ChanServ help` to get some help with registering/administering channels. It seems like a lot, but Freenode is the de facto gathering place for FOSS communities generally. Only good things can come of moving chat to Freenode. I'll drop the #AIMSICD-dev channel since you don't want to use it, and try to get a hold of the #AIMSICD channel like I mentioned before. Let me know when you've registered and are logged on. My nick is `curtisz` and I'm always idling.

**Comment by SecUpwN** [comment]
>Freenode is the de facto gathering place for FOSS communities generally. Only good things can come of moving chat to Freenode.

Thanks for telling me, @curtiszimmerman. We've been using [HipChat](https://www.hipchat.com/) until now, the positive thing there was that you can have locked rooms and share content not everybody shall see. How about storing messages in Freenode? I mean, if someone is not idling and joins the room, I guess all of the previous conversation and pictures are not visible to that person, I guess?

**Comment by curtiszimmerman** [comment]
I use HipChat at work and that is a nice feature, but with a little work it's simple to install a channel bot (for example Supybot, there are a million) to log messages somewhere, and use for example HTTP authentication to restrict access to the logs. Freenode of course has a million options for user access/authentication/administration of individual channels, but no built-in features for storing messages. I host channel bots and log servers for a couple of other projects going on a couple of years at least now, and it's something I could do for this project, as well, if you would like. Something to note, I prefer IRC over HipChat though, even with all of the functionality built into HipChat. A channel bot can handle those features and much more, and Freenode is incredible stable versus HipChat, which for me anyways crashes at least once or twice a week. Hidden conversations can be had a couple of different ways. "Unicast" private messages are built-in with `/msg`, and private group chats can be simulated by creating a private channel with a key/password and invite-only list of users. So there are ways to do those things in Freenode, for sure.

**Comment by E3V3A** [comment]
Freenode / IRC are inherently privacy-less! It is the prime target for automatic monitoring by pretty much anyone interested in monitoring anything on the iweb. I've often insisted in using SSL connections to IRC rooms, just to find them, dropped a few minutes later. SSL seem to be like TSA's Airport security controls, a theater for the masses. There are tons of secure chat solution out there, but IRC is not one of them.

**Comment by SecUpwN** [comment]
@curtiszimmerman, I am very thankful you've been getting hold of that guy who reserved `#AIMSICD` and perfectly understand that Freenode is likely the more wise choice for open source projects. But since our project has a special twist to it by stepping on the toes of spy organizations, we don't want to put contributors and possible whistleblowers at risk by using an unsecure chat system. I hope you'll also be happy if I just add a HipChat button to our [contact page](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Contact) where people can directly join in?

**Comment by curtiszimmerman** [comment]
Versus Hipchat? You guys really think Hipchat is not subject to the tactics of those same organizations that want the content of your chats? Atlassian is an American company, subject to NSLs in exactly the same way as Dropbox or Microsoft. And even if they weren't, are any of your developers using Windows?  Any of them? If any of you are using an insecure platform, then you might as well just put your communication out in the open unencrypted. If these people want the content of your chats, you are using the wrong technology to prevent them from getting it.

**Comment by He3556** [comment]
No we didn't think this chat is secure. We just need the features of HipChat and want a low barrier for people to join the discussion. If somebody preferred a secure channel we always open to do it in another way. If we have to install software, get registered or generate keys - no problem. But only for 1 on 1 communication. And in the end it's always a balancing between usability and security.

**Comment by SecUpwN** [comment]
>Versus Hipchat? You guys really think Hipchat is not subject to the tactics of those same organizations that want the content of your chats? Atlassian is an American company, subject to NSLs in exactly the same way as Dropbox or Microsoft.

Thanks for these important points, @curtiszimmerman. It really is no easy choice of which chat room to use. Personally, I like [Gitter](https://gitter.im/) much more than HipChat, but since we had the drawback with not being able to delete sensitive uploads (see `https://github.com/gitterHQ/gitter/issues/332`) and their devs not really wanting to address that matter, we ditched it. We know that Freenode is probably **THE** place to be for developers, but we'd have to cope with not being able to see previous conversations, losing pictures and rethinking the whole chat system, something that not every developer might be willing to do. Maybe you can join us on our HipChat to discuss this a little further? I have added a link to our contact page now. I am always open for other, more secure recommendations that offer clients for all platforms.

**Comment by darkerego** [comment]
Hey, would it be possible to implement a feature that would highlight suspected rogue base stations on the antenna map viewer? Perhaps they could be coloured red or something. Of course with a stong disclaimer explaining that it is possible that the station simply is not in the db yet. Seeing it on the map would help people both stay away from them, and for the adventurous amongst us to do some investigation, and determine what is going on.

**Comment by SecUpwN** [comment]
Hey @darkerego, please see #13. Your recommendation should be in there. However, we're currently lacking developers as it seems everybody is dealing with their own lives. Help us find developers, please.

**Comment by darkerego** [comment]
Okay, I will try to find some developers. By continuing to spread awareness about stingrays and fake BTS I am sure we can get more people on board. If I knew anything about Java I'd gladly help.

**Comment by agilob** [comment]
As something from category 'user friendliness' I would suggest translating application to more languages. Before that process starts strings.xml needs a few changes, app_name_short and app_name (and others?) should have attribute translatable="false".

**Comment by SecUpwN** [comment]
@agilop, I am still cleaning our repo and development is currently halted until tomorrow at the very latest . If you know how to make our app translatable, join #190 to discuss it there on how to do it best.

**Comment by SecUpwN** [comment]
This Issue has been solved with the cleanup of #371. Contact me for further improvements. Thanks!

**Comment by curtiszimmerman** [comment]
I've heard about a new, interesting project for team communication which sounds like it might be worth looking into: https://github.com/moose-team/friends

**Comment by E3V3A** [comment]
Thanks @curtiszimmerman, sound great, but it is neither using SSL or end-to-end encryption, nor offering code-highlighting AFAICT. So we're quite happy to stay with HipChat until then.

**Comment by curtiszimmerman** [comment]
I guess I should have clarified that I wasn't posting it as some kind of Hipchat replacement. I think it's pretty obvious that you guys are stuck on Hipchat. This seemed like an interesting alternative for an accessible, general chat for users.

**Comment by E3V3A** [comment]
@curtiszimmerman Ah, ok, that is a different story. Sure, we can look into it. (Just to clarify, we're not "stuck" on anything, we're just trying to balance between remaining flexible and minimizing the time required to curate and maintain all the various accounts, chats and what not.) Users are always free to use our XDA thread or our open channel at HipChat. Surely @SecUpwN have much more to say about this, since he's doing most of the PR and communications.

**Comment by SecUpwN** [comment]
Thanks for sharing this, @curtiszimmerman! I have looked into it and it seems neat, I am especially following https://github.com/moose-team/friends/issues/46. As for now, I am not intending to open yet another account anywhere else, our main focus is currently to cut down on the Issues and make some real progress. But I will definitely bookmark this and look at it once in a while. Please help us polishing the code.

**Comment by curtiszimmerman** [comment]
I think "stuck" was the wrong word for me to use. I understand what you guys are after for a chat, just thinking of things that might be useful in some way.

**Comment by TPS** [comment]
FWIW, #898 contains docs with some Stingray details.

**Comment by webcoderz** [comment]
Are you just adding this to every issue because I've gotten the same email
3 times

**Comment by TPS** [comment]
Sorry, @akrolla, only to those that mention stingrays specifically.

**Comment by webcoderz** [comment]
I get notifications to every email sorryi jumped down ur throat
I know u are just informing . try to get the info placed in the wiki or
readme.txt thays be the best plays for it @TPS
