### ISSUE TITLE
FBI: drop criminal cases rather than divulge Stingray details

### ISSUE THREAD

**Issue by rjh427** [SecUpwN/Android-IMSI-Catcher-Detector#368]
http://arstechnica.com/tech-policy/2015/04/fbi-would-rather-prosecutors-drop-cases-than-disclose-stingray-details/

I doubt there's any technical details that will help us here but this article does help illustrate the mentality and environment those things get used in. Okay to close this issue in a few days, after those who are curious have had a chance to see it.

**Comment by darkerego** [comment]
Thanks for sharing. That means it's likely worse and more prevalent than we thought, and that they are trying really hard to keep ISMI catchers out of the press. I bet if even 10% of the US population knew about this, perhaps we would see demand that the telecoms upgrade their infrastructure so that the base stations must authenticate themselves to the devices using modern encryption keys. So many big corporations use AT&T, I know of a specific few that do, and these companies are very concerned about trade secret leakage and corporate espionage. If they knew that often there is no encryption used whatsoever on the mobile network, than they would not be happy, and the telecoms would be forced to protect the consumers privacy.

**Comment by SecUpwN** [comment]
@rjh427, I really appreciate you updating us on these things, but please refrain from using our Issue tracker for spreading articles in the future. It just confuses developers and is not contributing to the code of our app. We have received feedback that developers in fact do not contribute because the see too many open Issues. If we let people add Issues that are not directly related to our app, we'll soon be dead. I hope you understand that. Here are your new recommended options:

1. Send me (or anyone else) the article directly, see our [contact page](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Contact).
2. Spread your links via Twitter and mention us `@AIMSICD`.
3. Post the link of [our website](https://secupwn.github.io/Android-IMSI-Catcher-Detector/) underneath those articles for people to join!

**Comment by rjh427** [comment]
:+1:

**Comment by TPS** [comment]
FWIW, #898 contains docs with some Stingray details.
