### ISSUE TITLE
More Good reasons to not use Google

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#400]
http://boingboing.net/2015/04/28/fbis-crypto-backdoor-plans-r.html

**Comment by SecUpwN** [comment]
Thanks @E3V3A! I am seriously thinking about not even adding an "installer" there as proposed in #202. How do you feel about completely ditching Google and staying with what we have already?

**Comment by E3V3A** [comment]
Sure. Just wanted to add this info somewhere, to inform people that their gov's and google app providers are even considering working with these bastards.

**Comment by SecUpwN** [comment]
It's a real shame. Android is such a wonderful operating system but what Google does with it and who they support is truly evil. Considering the fact that they've also bought [Boston Dynamics](http://www.bostondynamics.com/) and are now [building military-grade self-thinking robots](https://www.youtube.com/user/BostonDynamics), noone can tell me that they're not part of a future **war**.

I'd like to get the opinion of @He3556 and @DimaKoz for **closing** #202 **for good** since I feel stronger than ever that I **never** want our app to appear at GooglePlay (not even as a renamed or re-branded app)! We're developing this privacy and open source software, having our app (or even just an installer) on GooglePlay would enlarge our user base, but fuck that, we've gotta stand up for our freedom here!

**Comment by He3556** [comment]
yes, and please close other issues that are related to this discussion.
