### ISSUE TITLE
Move AIMSICD folder to ./Android/data/

### ISSUE THREAD

**Issue by agilob** [SecUpwN/Android-IMSI-Catcher-Detector#412]
What do you think about moving location of the folder with data from default location to `./Android/data/`? Currently the folder is easily accessible by users, can be deleted/modified by accident by user or cleaning applications.

Android supports 'private' data folders by design, current implementation of AIMSICD doesn't follow those 'guidelines' (not really guidelines, or I can't find them, but it's a good practice). Personally I find it annoying when apps mess with my folders, when they have their dedicated location to store data. Screenshots and link will tell you more.

>[All apps (root or not) have a default data directory, which is /data/data/<package_name>. By default, the apps databases, settings, and all other data go here. If an app expects huge amounts of data to be stored, or for other reasons wants to "be nice to internal storage", there's a corresponding directory on the SDCard (Android/data/<package_name>)](http://android.stackexchange.com/questions/47924/where-android-apps-store-data/47951#47951)
[more info](http://android.stackexchange.com/questions/46926/android-folder-hierarchy/46934#46934)

Where data is currently stored:

![screenshot_2015-05-04-16-27-58](https://cloud.githubusercontent.com/assets/2544251/7456305/65e524aa-f27b-11e4-9a8a-e6e0fb6ebf1e.png)

Where other apps store their data:

![screenshot_2015-05-04-16-27-50](https://cloud.githubusercontent.com/assets/2544251/7456306/68ab0a92-f27b-11e4-8e76-433856f5ebbc.png)

Example usage:
``` 
Log.i(TAG, getExternalFilesDir(STORAGE_SERVICE).getAbsolutePath());
Log.i(TAG, getExternalFilesDir(null).getAbsolutePath());
Log.i(TAG, getDataPath());

/storage/emulated/0/Android/data/app.id/files/storage
/storage/emulated/0/Android/data/app.id/files
/storage/emulated/0/Android/data/app.id/files/download/
```

**Comment by SecUpwN** [comment]
Good suggestion. Would like to hear both @DimaKoz and @E3V3A on this.

**Comment by E3V3A** [comment]
I'm fine with this, as long as it uses standard, non root writable, locations and doesn't mess it up for older APIs.

**Comment by darkerego** [comment]
I would like to add that when I use the "Export Database" function, in the newest WIP (v0.1.26-alpha-b00)  release and the previous release (v0.1.25-alpha-b35), I am prompted for root access for AIMSICD. However, if I deny root access, the files are still exported. I am on CM12 (5.1.1). Does this make sense to anyone?

**Comment by SecUpwN** [comment]
>...I am prompted for root access for AIMSICD...

Root should only be prompted for when hitting `AT Command Interface`. Please look into that @DimaKoz.

**Comment by darkerego** [comment]
Okay, that's what I thought. Let me know if you need debug logs. I reinstalled the app serveral times and downloaded it through various proxies to ensure the app was not tampered with, and the same thing happens. I also deleted the AIMSICD folder before each install, thinking perhaps I messed up the permissions.

Btw, may I suggest that you provide an additional way to verify the app's integrity when downloading from github? Perhaps a sha256sum in addition to the md5sum, or even your GPG key would do, as some people don't use 3rd party app markets like Aptoid. It is reasonable to be paranoid, considering the feds prefer to drop legal cases rather than disclose the stringray details to the public... I can only imagine that  apps like AIMSICD could be likely targets for malware injection.

**Comment by SecUpwN** [comment]
>Btw, may I suggest that you provide an additional way to verify the app's integrity when downloading from github? Perhaps a sha256sum in addition to the md5sum, or even your GPG key would do, as some people don't use 3rd party app markets like Aptoide. It is reasonable to be paranoid, considering the feds prefer to drop legal cases rather than disclose the stringray details to the public... I can only imagine that apps like AIMSICD could be likely targets for malware injection.

Sorry bro, but we're having way much heavier problems right now with people wanting to discredit us in public and making our GitHub repository get taken down. If you really want to make sure everything has not been tampered with, please compile the `development` yourself. Also see https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/66#issuecomment-85751526. Thanks.

**Comment by darkerego** [comment]
Okay I understand, and I have much respect for your guys for standing up for what is right. I guess it's time to learn how to compile an apk.

**Comment by E3V3A** [comment]
@darkerego  and @SecUpwN CM generally doesn't need root. Also, the reason root is required (AFAICR) is that is uses a command line option to call the `sqlite3` binary which is not always present in the default bin, to export a full monolithic dump. Please check that you got this, which I doubt.

**Comment by DimaKoz** [comment]
@E3V3A and @SecUpwN We had planned to redo the export (and backup) through the "cvs" files?

**Comment by E3V3A** [comment]
@DimaKoz I don't see any reason to redo. They work now, but the code for the CSV files is somewhat ugly. Also since we need to reformat several tables in the DB, we should wait with this export, as it require recoding of new table items. The dump will suffice for most practical purposes, and if user want the CSV, he can more easily do it manually using the `sqlite3 -csv ...` option as I have detailed in other issue thread.

**Comment by SecUpwN** [comment]
>Okay I understand, and I have much respect for your guys for standing up for what is right.

Sorry for having sounded like an asshole yesterday, @darkerego. I lacked sleep and got into an emotional outburst about a developer who I contacted and is now taking the lead in making us look like retards. In our eyes, the `MD5` should suffer here, compiling the `development` branch is [pretty easy](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Building).

>... Also since we need to reformat several tables in the DB, we should wait with this export...

Ok, I'm not sure how long this will take us to accomplish, but I feel it is time to get back to a useable and stable base we can rely upon with hacking as best as possible to finish #215. I've set it to `URGENT`.

**Comment by SecUpwN** [comment]
Digging deeper into this, it seems we should use [ContextCompat.getExternalFilesDirs()](https://developer.android.com/reference/android/support/v4/content/ContextCompat.html#getExternalFilesDirs%28android.content.Context,%20java.lang.String%29) for this since it supports Android 4.3 and lower. More to read and learn for me, a pull request for this is appreciated.
