### ISSUE TITLE
WIN DEATH when using Advanced User Settings

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#464]
@banjaxbanjo, our app currently **crashes** (and restarts if set in `Preferences`) when pressing `Detection Strings` and `Delete SMS` in `Prefeferences/ADVANCED USER SETTINGS`. Please have a look at the cause, it worked perfectly before. Let me know if you need more than my [filtered logcat](https://defuse.ca/b/0OA64sU0). Thank you.

**Comment by banjaxbanjo** [comment]
@SecUpwN That's strange did someone changed any of the code connected to any of my classes or strings because it was working for you before and now it throws an error, did you enter a weird detection string of any string in the advanced user menu that could cause a parsing error?

I cant make out whats causing it from the logcat you posted Sec.

Cheers

**Comment by E3V3A** [comment]
I can confirm this bug.

**Comment by SecUpwN** [comment]
>That's strange did someone changed any of the code connected to any of my classes or strings

@banjaxbanjo, this Issue might have been introduced with the changes made in https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/64e17250e304769b13e4abdf10cf13a362677506, but do not know where exactly to look at. Can you find anything in that commit that may be the cause?

**Comment by SecUpwN** [comment]
Hey guys, I have tested all previous Buildozer builds up to the point where the error did not occur. The error has been introduced with merging https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/ba1784dbaac40a8b2ee6ae32e8dbb025be1e57dc. @banjaxbanjo, can you find the error in there?

**Comment by banjaxbanjo** [comment]
Hey Sec,

I cant really check this till at my dev computer but these seem to be changed from the working dev:

I dont know if they are a problem yet till I test?
---------------------------------------------------------------------------------
app/src/main/java/com/SecUpwN/AIMSICD/smsdetection/AdvancedUserActivity.java

-            msgitems = new ArrayList<AdvanceUserItems>(); 
+            msgitems = new ArrayList<>(); <---dont know if this will cause an issue
----------------------------------------------------------------------------------
app/src/main/java/com/SecUpwN/AIMSICD/smsdetection/AdvanceUserBaseAdapter.java

-			convertView = l_Inflater.inflate(R.layout.adv_user_strings_list, null);
+			convertView = l_Inflater.inflate(R.layout.adv_user_strings_list, parent); <--- change this back to null so solve crash
-----------------------------------------------------------------------------------
app/src/main/java/com/SecUpwN/AIMSICD/smsdetection/AdvanceUserBaseSmsAdapter.java

-			convertView = l_Inflater.inflate(R.layout.adv_user_sms_listview, null);
+			convertView = l_Inflater.inflate(R.layout.adv_user_sms_listview, parent); <--- change this back to null so solve crash
------------------------------------------------------------------------------------
also these lines dont look right, can you confirm that sms detection is working with these changes?

I'm calling the lower case smsdetector.getSmsDetectionState() created in:
    public void startSmsTracking() {
        if(!isSmsTracking()) {
            Log.i(TAG,"Sms Detection Thread Started");
            smsdetector = new SmsDetector(this);
            smsdetector.startSmsDetection();
        }
    }
	
	I'm not calling the Class SmsDetector directly and dont know if this will cause a problem till I test;

-       if (smsdetector.getSmsDetectionState())
-       {
-        smsdetector.stopSmsDetection();
-       }
+
+        if (SmsDetector.getSmsDetectionState()) {
+            smsdetector.stopSmsDetection();
+        }
 
         Log.i(TAG, "Service destroyed.");
     }
@@ -175,7 +169,7 @@ public void setTrackingFemtocell(boolean track) {
 
     //SMS DETECTION
     public boolean isSmsTracking() {
-        return smsdetector.getSmsDetectionState();
+        return SmsDetector.getSmsDetectionState();<---- same here calling SmsDetector.Class rather than smsdetector I created.
     }

**Comment by E3V3A** [comment]
In general it is very confusing having different code with same name...let's try to avoid that. 

Anyway, the error seem related to the preferences, so it may have something to do with your changes (see PR) of not importing user preferences or something about using the `sp` instead of `dp`. See [this](http://stackoverflow.com/a/11638914):

> However if your text has to fit into a bounding-box of known size then you should use density independent pixels in order to ensure that the text always fits properly and that all characters are visible regardless of the users' setting.


```
E/AndroidRuntime(22595): 	at com.SecUpwN.AIMSICD.smsdetection.AdvanceUserBaseSmsAdapter.getView(AdvanceUserBaseSmsAdapter.java:48)
W/ActivityManager(587):   Force finishing activity com.SecUpwN.AIMSICD/.smsdetection.AdvancedUserSmsActivity
W/ActivityManager(587): Activity pause timeout for ActivityRecord{4262e068 u0 com.SecUpwN.AIMSICD/.smsdetection.AdvancedUserSmsActivity t9 f}
W/InputDispatcher(587): channel '42aed570 com.SecUpwN.AIMSICD/com.SecUpwN.AIMSICD.smsdetection.AdvancedUserSmsActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
```

**Comment by ziem** [comment]
I omitted third argument here:
https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/development/app/src/main/java/com/SecUpwN/AIMSICD/smsdetection/AdvanceUserBaseSmsAdapter.java#L48

I will fix it asap.
