### ISSUE TITLE
Only load cells in range on map

### ISSUE THREAD

**Issue by wvengen** [SecUpwN/Android-IMSI-Catcher-Detector#466]
Currently all cells are loaded from the database and shown on the map view. This takes a lof of time when there are many cell points (ike from OCID). I suggest to add a where clause to the database query on a lat/lng window, and re-query when changing the view.

I can imagine that #272 would be solved by this as well.

**Comment by E3V3A** [comment]
The problem with "range" is that it could mean anything.  Your phone could connect to towers 40+ km away...

**Comment by wvengen** [comment]
True. Though I fail to see why that would be an issue when showing the map - cells outside the view aren't shown anyway, right?

**Comment by SecUpwN** [comment]
>Though I fail to see why that would be an issue when showing the map - cells outside the view aren't shown anyway, right?

Right. I added you to our Buildozer account to get the APK for testing. Please test and close if fixed.

**Comment by wvengen** [comment]
Thanks! I found it to be ok on the branch I was working on (local build), but I'll test again with the new APK.

**Comment by wvengen** [comment]
Works!

**Comment by E3V3A** [comment]
Which build are you using? The latest I just tested # 137 crashed, so please state what you've tested and so on.

**Comment by SecUpwN** [comment]
@wvengen, please have a look at my https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/469#issuecomment-111830054. Even though I cannot confirm that the current Buildozer build is crashing (it works perfectly on my device), I know that Travis CI is now complaining about "missing translations", which it did not before since our app used to fall back to the default `values` folder when a translation has been missing. Please have a deeper look, I guess something in https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/467 may have messed it up.

**Comment by SecUpwN** [comment]
@E3V3A, if #469 is now fixed for you and build `#138` works, please test and close this.

**Comment by E3V3A** [comment]
Unfortunately the side-effect of this PR is that the map view is wrong, laggy and unresponsive until DB query is updated. Not good.

**Comment by wvengen** [comment]
This will also be reverted in #541.

**Comment by E3V3A** [comment]
Please re-test this issue now. (Using Buildozer build >= 211)
