### ISSUE TITLE
opening AIMSICD kills all radio (reception)

### ISSUE THREAD

**Issue by justbittin** [SecUpwN/Android-IMSI-Catcher-Detector#488]
I will have 6 bars on the reception meter, the moment I open AIMSICD it goes to 'no signal' with the dreaded circle with a line through it.  There is nothing I can do at this point and must reboot the phone.

Samsung Rush, Android 4.1, boost mobile network, not rooted.

**Comment by E3V3A** [comment]
Please read [this](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Submitting-Issues) and post a logcat and exact model number and country of operation. I've never heard of such a problem being related to our app. Somehow, I think this is something else going on...

**Comment by SecUpwN** [comment]
@justbittin, welcome to our project. As already stated by E:V:A, you're the first person reporting that our app would completely kill your radio connection. Please read and follow the guide mentioned and also make damn sure to post the relevant part of the logcat here (should be logged when the network is being killed), also tell us which version of AIMSICD you're using. Otherwise we'll close this as `INVALID` soon.
