### ISSUE TITLE
Mysterious leak in SQLiteConnectionPool

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#528]
I just got a logcat from latest build. One item caught my eye:
```
W/SQLiteConnectionPool( 360): A SQLiteConnection object for database '+data+data+com_SecUpwN_AIMSICD+databases+pk_sms_detection_db' was leaked!
Please fix your application to end transactions in progress and to close the database when it is no longer needed.
```
 Not sure if this is related to our other DB related issues like #486 and #487...

**Comment by E3V3A** [comment]
Suspicion:
> Maybe this occur when you have pending transactions (queued queries) waiting to be executed, but then some other thread (?) is trying to access DB to do something else? I don't think Android SQLite has enable multi-threading by default...

**UPDATE:**
This is all related to the fact we're not treating DB connections properly. See [these](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/215#issuecomment-118612414) references.

**Comment by banjaxbanjo** [comment]
@E3V3A I'd say its because I forgot to close a Cursor that's usually the what the main cause of DB leaks are and this shall be fixed in new overhaul. I like what you said about keeping the db open for app life and close on exit haven't the knowledge to tell if this is good or bad yet but here are some comments from a post on stackoverflow

#Do you "re-query" the database a lot?
Then it seems rectified to keep it open.

#Do you fetch different data each time you fetch something?
Again, it seems reasonable to leave it open (as you won't gain in caching the data instead).

#Are there any other applications accessing the same database?
If there is a risk for concurrency or blocking issues, it might be wise to close the database after finished reading/writing from/to it.

Generally I would say that you might gain more in caching data than in leaving the database open (contra closing it) when optimizing for performance.

**Comment by E3V3A** [comment]
Another thing about **caching** data: Since we're no longer on PC with HD's caching is rather useless. The EMMC's are almost as fast as RAM, so caching has little effect, AFAIK, and unless someone like to correct/prove me otherwise.

**Comment by E3V3A** [comment]
Please re-test this issue now. (Using Buildozer build >= 211)
