### ISSUE TITLE
Need to update DB ER diagram in Wiki and Issue #215

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#563]
Because of many recent changes in the DB we need to update the Entity Relationship diagram in the Wiki, and as displayed in issue #215, and possibly elsewhere. My most recent **aimsicd.sql** file can be found [here](https://github.com/E3V3A/woork/blob/development/aimsicd5.sql). New diagram need to correspond to that. 

However, we probably should integrate all changes before publishing diagram.

**Comment by SecUpwN** [comment]
@E3V3A, since I host all pictures on our secured SpiderOak account, please just sent me the new diagram via E-Mail and I'll update it ASAP. I guess it makes sense updating it now, but highlighting the things that still have to be implemented with a separate color and a small legend below the diagram.
