### ISSUE TITLE
Release v0.1.33-alpha-b00 immediately crashes

### ISSUE THREAD

**Issue by TPS** [SecUpwN/Android-IMSI-Catcher-Detector#596]
… even after reboot, so I must revert to v0.1.32-alpha-b00, but, since the current release will not stay open long enough to get a log, how do I help? What can I provide?

Edit: I figured it out.  I think another issue mentioned backend database changes, so wiping the data & restarting the app solved it, but it'd been good if that had been handled much more gracefully.…  Maybe some sort of database version check?

**Comment by SecUpwN** [comment]
@TPS, since our app is still in `ALPHA` stage, full uninstall of the old version and a fresh install is the common procedure. Installing the new version over the old app will continue to be possible - this time we've had major changes in the database and therefore a fresh install is necessary. Enjoy the new release!

**Comment by TPS** [comment]
@SecUpwN I do agree with that, but, at some point, preferably sooner, there should be some sort of standard database version check performed for when we get OUT of alpha, so I'd like to suggest that.

**Comment by SecUpwN** [comment]
@TPS, as already said, please file a separate Issue for this suggestion!
