### ISSUE TITLE
Check database version and prompt when incompatible

### ISSUE THREAD

**Issue by TPS** [SecUpwN/Android-IMSI-Catcher-Detector#597]
N.B.: This suggestion is especially for when AIMSICD goes beta & beyond (as @SecUpwN reminds me, the current correct alpha behavior is to uninstall/reinstall, NOT in-place install), but should be implemented sooner, so that it doesn't cause problems down the road.

As I mentioned in #596, database changes between versions (I further suggest in either direction, both up- or downgrading) should be handled more gracefully than the current behavior of immediately crashing upon run.  I'd recommend, as in the title (currently ;), having a database version checked upon run (e.g., after an in-place different-version installation), & popup a prompt with options if that version is incompatible with the current app version.

I further envision the options being something like:

* **Abort** (meaning immediately gracefully quit out while leaving data untouched, just in case previous version should be reinstalled)
* **Reinitialize** (something simpler would be better that means "Wipe & start new," with sub-option to keep backup of old database as-is)
* **Upgrade** (eventually, & when appropriate) - which means, of course, as much as possible, rebuild the old version database into the newer version, with same sub-option to keep backup

**Comment by TPS** [comment]
@SecUpwN Thanks for cleaning that up.…  Of course, I knew you would. ;)

**Comment by SecUpwN** [comment]
>Thanks for cleaning that up.…

No problem, you're welcome.

>Of course, I knew you would. ;)

Yes, I'm nitpicky and love what our developers do, thus proper Issues help them to know what to code.

**Comment by E3V3A** [comment]
We're already doing this check [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/search?utf8=%E2%9C%93&q=DATABASE_VERSION&type=Code) but I have no idea to what extent it works. I only know we just reset the version "1" after big overhaul. So yeah, delete your old DB!

**Comment by TPS** [comment]
@E3V3A I think maybe order of check on run.…  From the behavior I experienced, the database is accessed immediately upon run, without any sort of mitigating checks before, so the above requested improvement is necessary. ☺

**Comment by SecUpwN** [comment]
@DJaeger, would you please add your thoughts to this idea? Thank you!

**Comment by DJaeger** [comment]
At least for later release versions we should do a versioning of the database.
If the app detects an update it have to migrate the database to the new schema.
We can also allow downgrades by the database, but only version by version, so no jump back of 2 or more versions.
For this to work we have to release an "database update preparation" (this is what should be written in the changelog to not confuse user with words like "downgrade") version, which simply detects downgrades of the app and migrates back the database, since we can not take care of the back migration in older versions (which don't know the new schema).

**Comment by TPS** [comment]
@DJaeger That's actually a lot more than I envisioned. ☺  Should the backup path that's been mentioned be entirely separate, or somehow related to this up-/downgrading path (internally)?

**Comment by DJaeger** [comment]
@TPS: I'm not sure what you mean.
Before changing (up-/downgrading) the database it should be backed up.
Since you probable will reinstall the app if it fails your backup will be lost if it is located inside the data directory of the app.
I think we should use the existing backup function to not duplicate backup code, but I can nowhere in the app determine where it is located.

**Comment by TPS** [comment]
@DJaeger I'm wondering if the database backup / restore functionality should expanded into also including that ↑↓grading functionality, just to keep it all contained & easier to maintain, especially as I expect the number & type of database(s) to change again, until they're finalized by beta.

**Comment by DJaeger** [comment]
Of cause we could do all the db up-/downgrade in the import function and after updating the app with needed db migration simply trigger a backup and a following import and just do not delete the backup.
But keep in mind that we should not take care of to much versions to not mess up the code.

**Comment by johanw666** [comment]
I'd say just look at how other projects do it: see https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/database/DatabaseFactory.java for an example. Shouldn't be too difficult to implement something like that.

**Comment by E3V3A** [comment]
App is in **alpha** and after Beta stage, the DB should be the same for the rest of its life. And if it is not, then this is a suggestion for additional very low priority work that we have no resources of completing.
