### ISSUE TITLE
F-Droid unable to install the app

### ISSUE THREAD

**Issue by Montagnard65** [SecUpwN/Android-IMSI-Catcher-Detector#607]
Hi,
When I try to download and install the Android IMSI-Catcher-Detector app on the F-droid store (with the + button or by clicking on the Version 0.1.28-alpha-b00 button), F-Droid try to launch the download  but stop immediately (the download window open and close directly) and tell me "not installed"...
Did i missed something ? Is there a way to correct this "bug" ?

Thanks!

For Information : I have a Nexus 5 on Android 5.1.1 with F-Droid on Version 0.91

**Comment by TPS** [comment]
@Montagnard65 Current stable F-droid is 0.95.1 & current AIMSICD is  https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/releases/tag/v0.1.34-alpha-b00, which I think corresponded to a lot of database backend updates on each app.…  Do you have any problems installing anything _else_ with F-droid?  What happens when you uninstall AIMSICD (which is currently required) & install directly from the provided link?

**Comment by SecUpwN** [comment]
Good morning @Montagnard65, thanks for reporting this. Please try what has been suggested above: Completely uninstall AIMSICD and make sure to install our app from either Aptoide *or* F-Droid (which builds our app by themselve and uses their own signature). Alternative: [Direct Download](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/releases/). Works now?

**Comment by Montagnard65** [comment]
Hi,
Thanks for your replies, with the last version of F-Droid (0.95.1), the download of v0.1.34-alpha-b00  works!
