### ISSUE TITLE
_

### ISSUE THREAD

**Issue by NicholaiGit** [SecUpwN/Android-IMSI-Catcher-Detector#610]

**Comment by banjaxbanjo** [comment]
@NicholaiGit hey all depends on the phone, some phones use smd and some phones the ports are located somewhere else I think its input/radio or dev/input/radio. They wont be called smd if not in dev directory so try sending AT commands to all of them, also plug your phone into a computer to see will a COM port show up a lot of times you can send AT commands to these ports on windows use putty.exe, you can get com port name from device manager and in linux when you connect your phone type dmesg |grep tty and if you see ttyACM0 or something similar you can send AT commands to this.

**Comment by NicholaiGit** [comment]
That's an amazing response, thank you!

Whenever I try to access smd0, it tells me that it doesn't exist. I can locate the file and type ls /dev/smd0 and see that it exists and is owned by radio.radio. I have been trying for actual days now trying to fix it. When I try connect my HTC One M7 device, how would I get the IP:Port to connect to?

Also the /dev/radio does not contain anything, and the input/radio does not either.

It would be a dream to get this working since I have been trying for literally over 24 hours.

Thank you!

----- Reply message -----

**Comment by banjaxbanjo** [comment]
@NicholaiGit Hey I don't know what your mean ip:port because you don't connect to the com port in this way.

Make sure you've proper usb drivers for your phone if using windows and not all phones have a com ports. If your lucky one will show up in device manager when your connect your phone, it  might show up as modem or something like that. If so click on it and get com port number will be something like COM11 or a random number.

Once you have this port number open putty and go to serial connection and enter com port number and connect. You can enter you at commands then with putty.

On android try for ports in dev/socket/radio also

**Comment by NicholaiGit** [comment]
Thank you once again for the great reply.
I will try to do that. I cannot find my radio folder tho, it seems like an endless loop for this.

I appreciate your help a lot, and if you don't mind, I'd love to have you on Skype or something like that, you seem like a very experienced user.

----- Reply message -----

**Comment by banjaxbanjo** [comment]
I charge €100 per hour for Skype consultation😉 everything I learnt was from the google machine.

Sent from Yahoo Mail on Android
