### ISSUE TITLE
Empty IMSI Information

### ISSUE THREAD

**Issue by SecUpwN** [SecUpwN/Android-IMSI-Catcher-Detector#745]
After fixing #717 our app does not display the `IMSI` anymore. @jensstein, do you find the cause?

**Comment by jensstein** [comment]
yes, it's because you are not setting any text in it's textview when you get it at DeviceFragment.java:L174.
i can make you a pull request with my original patch if you are still interested :)

**Comment by SecUpwN** [comment]
>i can make you a pull request with my original patch if you are still interested :)

@jensstein, I have already applied your patch for #717. I'd appreciate a pull request only for this Issue.

**Comment by jensstein** [comment]
ah.. no, you didn't apply my patch. you only took some of it and you forgot the attribution. if you had used either git or patch to apply it, you would have had another result.
so the most sensible would be to revert 7717cad0098a0c799fffabb907d7dbfb6e89a9be, esspecially because it doesn't do what it says.
and i will put in a pull request :)

**Comment by SecUpwN** [comment]
>so the most sensible would be to revert 7717cad0098a0c799fffabb907d7dbfb6e89a9be, esspecially because it doesn't do what it says.

Thanks for having a closer look at what I did. Reverted and will instantöly merge your awesomeness. :+1:

**Comment by jensstein** [comment]
cool, glad i could help :)
