### ISSUE TITLE
Need App Tester with OsmocomBB phone

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#75]
Hi! We're at a point in our development where we need testers who have an [OsmocomBB](http://bb.osmocom.org/trac/wiki/Hardware/Phones) phone that we can use to test our detector with. In particular we need to test:

- [x] Silent SMS
- [x] IMSI-catcher functionality by fake BTS (i.e. osmo-phone in BTS mode.)
- [x] Anti-catcher operations

Checked box for current testing and Unchecked boxes for future testing.

**Comment by SecUpwN** [comment]
@mspublic, I'm afraid I lost your email address. Please get in touch with me via E-Mail (I have a key now which I will send to you before starting a conversation again). This message will be deleted afterwards.

**Comment by 0x7678** [comment]
@E3V3A , @SecUpwN  my apologies for the long delay, however i have findings that might help? , my tests with OsmocomBB were as follows, not detectable under 2G, under 3G, 4G/LTE OsmocommBB BTS doesn't work and ARFCNs that use frequencies 1700/1800 it wouldn't work, the probable cause might be because OsmocomBB attaches  and (blocks) the BTS that is strongest as it doesn't have a sync clock (USRP uses GPSDO/Clock Tamer) this might be one probable cause for lack of detection ,then again I have nt taken my time really well with it, will attach pictures when I get back home.

**Comment by SecUpwN** [comment]
@mspublic, I'm afraid I lost your email address. Please get in touch with me using my **new E-Mail address** (click my name here). This message will be deleted afterwards. Thank you very much!

**Comment by SecUpwN** [comment]
@0x7678, any news? If you can ensure me that you'll be around for continuous testing of our app, I'd like to grant WIKI access to you so that you can publish and edit results in a fresh page on [our WIKI](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/).

**Comment by 0x7678** [comment]
On 2015-07-05 00:38, Security: Pwned. wrote:
> @0x7678 [1], any news? If you can ensure me that you'll be around for
> continuous testing of our app, I'd like to grant WIKI access to you so
> that you can publish and edit results in a fresh page on our WIKI [2].
> 
> 
> --
> Reply to this email directly or view it on GitHub [3].
> 
> 	*
> 
> Links:
> ------
> [1] https://github.com/0x7678
> [2] https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/
> [3]
> https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/75#issuecomment-118579339
Hi back at you SecUpwN , I hope you got my last messages, no reply from 
them, however I wouldnt mind adding content on the WIKI. Thank you.
-- 
Regards
=================================
Jade Solomon
Information Security Consultant
Cell: +254 701 888 445
WebSite: http://0x7678.com
Blog:  http://blog.0x7678.com
--------------------------------------------------------------------------------------------------------------------------------
Disclaimer :
The information contained in this e-mail may be confidential, 
proprietary, and / or legally privileged. It is intended only for the 
person or entity to which it is addressed. If you are not the intended 
recipient, you are not allowed to distribute, copy, review, retransmit, 
disseminate or use this e-mail or any part of it in any form whatsoever 
for any purpose. If you have received this e-mail in error, please 
immediately notify the sender and delete the original message. Please be 
aware that the contents of this e-mail may not be secure and should not 
be seen as forming a legally binding contract unless otherwise stated. 
Thank you.

**Comment by SecUpwN** [comment]
>Hi back at you SecUpwN , I hope you got my last messages, no reply from them, however I wouldnt mind adding content on the WIKI. Thank you.

I did not receive anything else other than what you wrote in this Issue. Anything worth publishing?

**Comment by 0x7678** [comment]
On 2015-07-09 02:42, Security: Pwned. wrote:
>> Hi back at you SecUpwN , I hope you got my last messages, no reply
>> from them, however I wouldnt mind adding content on the WIKI. Thank
>> you.
> 
> I did not receive anything else other than what you wrote in this
> Issue. Anything worth publishing?
> 
> --
> Reply to this email directly or view it on GitHub [1].
> 
> 	*
> 
> Links:
> ------
> [1]
> https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/75#issuecomment-119840927
Let me see what I can gather and email the details to you say monday?
-- 
Regards
=================================
Jade Solomon
Information Security Consultant
Cell: +254 701 888 445
WebSite: http://0x7678.com
Blog:  http://blog.0x7678.com
--------------------------------------------------------------------------------------------------------------------------------
Disclaimer :
The information contained in this e-mail may be confidential, 
proprietary, and / or legally privileged. It is intended only for the 
person or entity to which it is addressed. If you are not the intended 
recipient, you are not allowed to distribute, copy, review, retransmit, 
disseminate or use this e-mail or any part of it in any form whatsoever 
for any purpose. If you have received this e-mail in error, please 
immediately notify the sender and delete the original message. Please be 
aware that the contents of this e-mail may not be secure and should not 
be seen as forming a legally binding contract unless otherwise stated. 
Thank you.

**Comment by SecUpwN** [comment]
>Let me see what I can gather and email the details to you say monday?

Perfect. Please make sure to use the *latest* release of AIMSICD, it will be published on sunday.

**Comment by 0x7678** [comment]
On 2015-07-09 02:54, Security: Pwned. wrote:
>> Let me see what I can gather and email the details to you say
>> monday?
> 
> Perfect. Please make sure to use the _latest_ release of AIMSICD, it
> will be published on sunday.
> 
> --
> Reply to this email directly or view it on GitHub [1].
> 
> 	*
> 
> Links:
> ------
> [1]
> https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/75#issuecomment-119845215
Awesome, will do.
-- 
Regards
=================================
Jade Solomon
Information Security Consultant
Cell: +254 701 888 445
WebSite: http://0x7678.com
Blog:  http://blog.0x7678.com
--------------------------------------------------------------------------------------------------------------------------------
Disclaimer :
The information contained in this e-mail may be confidential, 
proprietary, and / or legally privileged. It is intended only for the 
person or entity to which it is addressed. If you are not the intended 
recipient, you are not allowed to distribute, copy, review, retransmit, 
disseminate or use this e-mail or any part of it in any form whatsoever 
for any purpose. If you have received this e-mail in error, please 
immediately notify the sender and delete the original message. Please be 
aware that the contents of this e-mail may not be secure and should not 
be seen as forming a legally binding contract unless otherwise stated. 
Thank you.

**Comment by SecUpwN** [comment]
@0x7678, have you been testing our app with your OsmocomBB phone yet?
We need some hard facts and continuous testing. Thanks for replying here!

**Comment by 0x7678** [comment]
Hi Everyone, @SecUpwN and @E3V3A my apologies for being too silent, this are the tests so far done with OsmocomBB :

 Silent SMS (currently working on modifying OpenBTS to allow sending silent SMSs)
 IMSI-catcher functionality by fake BTS (i.e. osmo-phone in BTS mode.)
     AIMSC doesn't detect the fakeBTS
     User can still proceed with SMS/VOICE without any detection as the OsmocomBB BTS interrupts
the current serving BTS (so as to set its ppm frequency offset) it 'blocks' connection to the serving BTS and assumes the role of a BTS, this is one way it avoids being noticed as it acts as a 100% replica  of the serving BTS .

Anti-catcher operations:
Anti-Catcher operations that I have noted detect it (ONLY on the cryptophone [still mitigable]) is when the OsmocomBB BTS(IMSI catcher)  has no cell neighbors.
If OsmocomBB BTS is setup not to use encryption, this also makes it detectable (on the cryptophone but not on AIMSC)

Please see screenshots attached.
![aroutjcnxhqsimxxqetzfgmac66tm0ol6xjd-2yb9op1](https://cloud.githubusercontent.com/assets/8582348/11614397/f596bb28-9c52-11e5-896d-af045fa8f61e.jpg)
![auzceff9tark6lbw-ucxrba3oklzzdjq0co12qca_lss](https://cloud.githubusercontent.com/assets/8582348/11614398/f5975c22-9c52-11e5-987a-e53f025b9f77.jpg)

**Comment by SecUpwN** [comment]
Thanks @0x7678 for adding your results here. You see, I would like to close this Issue and let you maintain a table in our WIKI with ongoing test results of the things listed in OP. Possible for you? ;-)

**Comment by 0x7678** [comment]
Hi @SecUpwN , no problem, it would definitely be my pleasure :100:

**Comment by SecUpwN** [comment]
>Hi @SecUpwN , no problem, it would definitely be my pleasure :100:

Awesome, @0x7678! Please tick which test results you can provide in the OP! You've been elevated to status `COLLABORATOR`. Please craft a neat and useful [markdown table](http://www.tablesgenerator.com/markdown_tables) and add it [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/wiki/Detection-Results). When testing, please make sure to always use the latest version from our compiled `development` branch. Would you like me to add you to our [Buildozer Builds](https://buildozer.io/) so that you can use the automatically compiled version?

**Comment by 0x7678** [comment]
@SecUpwN thank you, sure you can add me to the Buildozer builds, let me add the results.
