### ISSUE TITLE
Can't install v0.1.39.1-alpha

### ISSUE THREAD

**Issue by benefaktorix** [SecUpwN/Android-IMSI-Catcher-Detector#771]
Hi, I don't if any of you have ran into this as well but - i can't install 39.1 alpha. When I follow my usual procedure of downloading the apk and allowing the unknown sources to install, the usual screen to update the app pops up but the "Install" button is not clickable, while all the rest (cancel, app permissions, etc.) are. Stock android 4.4.2 Samsung s4

**Comment by SecUpwN** [comment]
>Hi, I don't if any of you have ran into this as well but - i can't install 39.1 alpha.

Good mroning @benefaktorix. From which version did you try to update from? In fact, our previous automatic release `0.1.39-alpha` had a problem with the signature, so you cannot update from there. I'll add a special note on the release in question right now. To make a long story short: Please update from `0.1.38-alpha` directly to `01.39.1-alpha` either via GitHub releases or XDALabs. Did this help you?

**Comment by Nordlenning** [comment]
I encountered the same problem on my Sony V lt25. I removed version 0.1.38a and tried again to install version 0.1.39 downloaded from github. It worked! & the app works fine so far, 3 days.

**Comment by larsgrefer** [comment]
I've tested on my Nexus 5 (Stock Android 6.0.1):

(Note the difference between `38`, `39` and `39.1`)

Updating from `0.1.38-alpha` to `0.1.39.1-alpha` works

Updating from `0.1.38-alpha` to `0.1.39-alpha` or from `0.1.39-alpha` to `0.1.39.1-alpha` won't work, because `0.1.39-alpha` has another signature than `0.1.38-alpha` and `0.1.39.1-alpha`
