### ISSUE TITLE
Build number null 

### ISSUE THREAD

**Issue by f3ndot** [SecUpwN/Android-IMSI-Catcher-Detector#773]
Tiny and small bug, but a bug nonetheless. 

Latest version installed from f-droid.org, Nexus 6P.

Expect either a build number or human readable handling of null case

http://imgur.com/lkcgIsL

**Comment by SecUpwN** [comment]
Nothing to worry about, @f3ndot. The build number is only shown on Builds that have been created with our internal Buildozer account so that we can test the very bleeding edge APK from branch `development`. But you are right, we should probably make the build entry fully vanish on released APKs. @larsgrefer, would you please have a look at this and see if you can improve that part of our code?
