### ISSUE TITLE
FemtoCell detection removing

### ISSUE THREAD

**Issue by tt3mm** [SecUpwN/Android-IMSI-Catcher-Detector#789]
It seems to me, that there is a whole feature, femtocell tracking wired in the code, without really using it.
Also at the root of it there is a comment: 
```
// TODO: Consider REMOVAL!   See issues: #6, #457, #489
// TODO: Summary: We can detect femtocells by other means, using network data that we already have!
```
I saw there are long threads about it, but can anybody give a short summary why is it still in the code?
I have no emotional attachment, so I would gladly delete it from everywhere if there is no need for it.

**Comment by SecUpwN** [comment]
>I saw there are long threads about it, but can anybody give a short summary why is it still in the code?

What exactly do you mean? I guess you are talking about the comments? Those still need cleanup, something I've aleady started and need to continue. A detailed list of which files still need cleanup can be found [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/672#issue-121037185). Regarding the full removal of FemtoCell detection: I am voting against doing so since we've already spend considerable time implementing these things from #6. But what I'd definately consider, is to improve (or even replace) the existing detections in a way that makes it easier to maintain and expand upon. I've just re-read parts of the old discussion and realized that we likely did not always listen to what our (now gone) project inventor once said - like the useful things mentiuoned in https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/6#issuecomment-120662285. What we'd need is some developer specifically digging into and improve that part of our code.
