### ISSUE TITLE
AIMSICD enforces cell changes and downgrades to HSPA

### ISSUE THREAD

**Issue by Nordlenning** [SecUpwN/Android-IMSI-Catcher-Detector#796]
I discovered that if I make or receive a phone-call while AIMSICD is running
I get alarms vibrating and yellow warning icon telling me to leave my house.

Restarting of the app is required to get rid of the (PSC:) & the yellow Warning Icon.

My Cell-number (CID) & (LAC) also changes when calls are made, but returns to normal if I 
minimize the app (background) & up again after the call.

Both InViu OpenCellID app(I use to collect & upload cells with) & RF Signal Tracker reports
the same change of cell & downgrading to HSPA while calls are made.

If I make a new call without restarting the app, the alarms goes on vibrating again.
I don't know if this is related to AIMSICD not supporting LTE as mentioned in #442.

Looks like phone calls gets downgraded to HSPA & directed to another cell on my Network. So every time I make or receive phone calls Alarms goes on. :). This will affect all users in my country since we have LTE all over.

![aimsicd2](https://cloud.githubusercontent.com/assets/17292772/13368440/392f2a08-dce2-11e5-99b7-4cf7b07273d6.png)

**Comment by SecUpwN** [comment]
>I get alarms vibrating and yellow warning icon telling me to leave my house

Good morning @Nordlenning, I'm sorry for your troubles, I can confirm this bug even without calling: It seems as if the network mode changes every few seconds and then then your phone certainly vibrates when this is option is checked. I've changed the title of your Issue to something more appropriate so that our developers know what specifically to have a look at - I hope you agree with this. As well, I've elevated the priority of this Issue and hope @tt3mm will have a look at it soon to se if our code is messed up somewhere. Meanwhile, feel encouraged to turn of vibrations in the `Preferences`. Thank you.

**Comment by tt3mm** [comment]
I am trying to reproduce it.
If a call connects, then yes, the CID changes, the yellow alarm turns on.
My calls are always HSPA or HSPA+, and I didn't see any correlation of changing, when the call connects.

Can someone post any ideas, or logs?

**Comment by Nordlenning** [comment]
I will try to explain my thoughts. 
In the picture above there is 4 screenshots, lets call them 1,2,3,4 from left.

Picture 1 is the waiting state. Nothing happens. Green icon, alles OK.
Picture 2 is the call state (call is made), AIMSICD gives warnings.
The phone changes cell for the phone call from LTE to HSPA & PSC shows up.

Picture 3 is after the call has ended  & the phone connects back to its normal LTE cell number.
PSC is still there & phone states it's on LTE cell & the cell number is the LTE cell. 

Picture 4 is the phone after 5 minutes in waiting state & the PSC is still there on LTE Cell 
& Yellow Icon, AIMSICD does not return to picture 1, as I would expect  it to do.

So picture 1 & 4 should (could) be the same after the call has ended.(without PSC & Yellow icon).
That's why I called it refresh/reset after call connection has ended.(return to picture 1).
AIMSICD stays with picture 4. Yellow Icon + PSC.

That means that everybody who is normally connected to LTE Network will see pic 4 all the time
if they have made or received a phone call. Yellow Icon + PSC.

This will affect all in my country since everybody is normally on LTE.
The solution could be to manually lock the phone to HSPA, but I don't know anybody who would.
If you restart AIMSICD everything is OK, until next call is made I/O.

I think I heard somewhere that Phone Network are set up to do this automatic, 
downgrade phone calls from LTE to HSPA do to small amount of data needs(for calls).

Hope this is of any help. I can upload logs if wanted.

**Comment by SecUpwN** [comment]
>Hope this is of any help. I can upload logs if wanted.

Thanks for assisting. Yes, please anonymize your logfiles (remove all personal data) and upload theme on [PIEBIN](https://defuse.ca/pastebin.htm), then post the link to the logfiles in this Issue so that devs can have a look.

**Comment by Nordlenning** [comment]
Both cells in use exists in ocid database. https://defuse.ca/b/KXgmCNcPLSm6HjpzzvtTvk
Hope it can be of any help.

**Comment by agilob** [comment]
>I discovered that if I make or receive a phone-call while AIMSICD is running

There it is, your issue is invalid. Your network operator downgrades your connection to the **cheaper** one for calls **and** texts. Phone calls and texts are based on **signaling protocols**, while LTE is a data transfer protocol. Every call and text goes through cheaper to maintain links. It would be waste of money and computing powers to let you make phone calls over LTE, think about audio input and output bitrate, how much megabyes would you use during a one minute call. Operator would have to subtract this data transfer to your data packet allowance. AIMSID raises invalid alert, again.

**Comment by SecUpwN** [comment]
>AIMSICD raises invalid alert that scares people, again.

@agilob, thanks for solving this Issue by clarifying what really happened. Please open a fresh Issue with a proposal on how we should improve our log messages so that people do not get scraed off.

**Comment by agilob** [comment]
>@agilob, thanks for solving this Issue by clarifying what really happened. Please open a fresh Issue with a proposal on how we should improve our log messages so that people do not get scraed off.

Title of this issue should be changed to "AIMSICD raises alert during a call", I think there was an issue like that before.

AIMSICD should has a kind of fuzzy algorithm which decides what threat level is instead of hardcoding a few statements like "LAC changed so let's rise an alarm". This is really wrong and users proved it in many places before, eg. no internet connection for a few app restarts raises an alert, new cell missing in OCID raises an alert, travelling with high speed raises an alert, not having OCID key and having internet connection while travelling... raises an alert. This is broken behaviour that scares users who report us invalid issues.
I responded to at least 4 threads where users were reporting false positives I also sent you an email with suggestions... nvm me, I'll just keep being ignored.

**Comment by Nordlenning** [comment]
Thank you for confirming my suspicion @agilob. Phone Networks are set to do this downgrade by default.

This is also confirmed by my Network supplier & it goes for ALL Phone Networks by default.(LTE)
So this automatic default downgrade could be taken into consideration since it affect ALL users in many countries.

It seem to me that the Alert gets triggered at line 448 in the uploaded log.
I/CellTracker( 5040): ALERT: Connected to unknown CID not in DBe_import: 14Notofintrest.(HSPA Cell).
I was not so sure this Alert was triggered by this downgrade, so I did a second test.
I locked my phone on HSPA & made a connected call to one of my other phones to see what happened. 

I got AIMSICD Alert with yellow icon on AIMSICD startup, & took a closer look at the log. The Alert 
seems to be related to this HSPA cell not being recognized by AIMSCID as a known cell.
& the Yellow Alert Icon stays.

As I stated above, this HSPA cell is a well known cell in OCID database, so it should not trigger Alert i think, but it does, & AIMSICD states "CID not in DBe_import:". Triggering Alert.

"AIMSID raises invalid alert that scares people" Should AIMSCID do this? making people not using it?.

This Alert may be a Db issue I guess.  Just my humble thaughts  : )

**Comment by agilob** [comment]
>So this automatic default downgrade could be taken into consideration since it affect ALL users in many countries.

That's not 100% true, in some African countries where Google and facebook are internet, they are only ISPs and they offer only their "online" services, you don't have GSM but only 3G, but those countries are under very heavy surveillance anyway and we can't go anything even if we would try. Good job India on waking up on time.

**Comment by SecUpwN** [comment]
This Issue is being closed due to being `INVALID` as found out in https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/796#issuecomment-191096296.

>Title of this issue should be changed to "AIMSICD raises alert during a call", I think there was an issue like that before.

@agilob, I have not found the Issue you mentioned and will open a fresh Issue to improve this situation.
